import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {resolveState,matchLanguage,storeEntries,safeStoreUrl,selectScreenshots,selectCopy,groupApps} from '../apps/state.mjs';
const catalog=JSON.parse(readFileSync(new URL('../apps/catalog.json',import.meta.url)));const languages=Object.keys(catalog.languages);
const state=(query,browser=[],ua='',touch=0)=>resolveState(query,languages,catalog.apps,browser,ua,touch);
test('explicit language, regional language and English fallback',()=>{assert.equal(state('?lang=ja',['ko']).lang,'ja');assert.equal(state('?lang=es-419').lang,'es');assert.equal(state('?lang=zh-Hant-TW').lang,'zh-TW');assert.equal(state('?lang=unknown',['vi','ko-KR']).lang,'ko');assert.equal(state('', ['vi']).lang,'en');assert.equal(matchLanguage('zh-CN',languages),'zh-CN');assert.equal(matchLanguage('zh-Hans-SG',languages),'zh-CN');assert.equal(matchLanguage('pt-BR',languages),'pt-BR');assert.equal(matchLanguage('pt-AO',languages),'pt');});
test('every source app is identified by stable ID and package alias',()=>{for(const app of catalog.apps){assert.equal(state('?from='+app.id).source,app.id);for(const alias of app.aliases)assert.equal(state('?from='+alias).source,app.id);}});
test('hostile and malformed query values are ignored',()=>{for(const query of ['?from=%3Cscript%3E&lang=%00&platform=javascript:alert(1)','?from=unknown&lang=%E0%A4%A&platform=windows','?from=&lang=&platform=']){const result=state(query);assert.equal(result.source,null);assert.equal(result.lang,'en');assert.equal(result.platform,null);}});
test('OS preference leaves both store routes available',()=>{assert.equal(state('?platform=android',[],'iPhone').platform,'android');assert.equal(state('?platform=bad',[],'Android').platform,'android');assert.equal(state('',[],'Macintosh',5).platform,'ios');const stores=catalog.apps.find(a=>a.id==='batting-log').stores;assert.deepEqual(storeEntries(stores,'android').map(([key])=>key),['android','ios']);assert.equal(storeEntries(stores,'ios').length,2);assert.equal(storeEntries(catalog.apps[0].stores,'ios').length,1);});
test('external links are HTTPS and strictly restricted to store hosts',()=>{for(const value of ['javascript:alert(1)','https://apps.apple.com.evil.test/a','//play.google.com/a','https://evil.test'])assert.equal(safeStoreUrl(value),null);for(const app of catalog.apps)for(const url of Object.values(app.stores))assert.ok(safeStoreUrl(url));});

test('image language fallback is explicit and app-specific',()=>{const dart=catalog.apps[0];const soccer=catalog.apps.find(a=>a.id==='starting-xi');assert.equal(selectScreenshots(dart.screenshots,'de').language,'de');assert.equal(selectScreenshots(soccer.screenshots,'de').language,'en');assert.equal(selectScreenshots(soccer.screenshots,'de').fallback,true);assert.equal(selectScreenshots(soccer.screenshots,'ja').fallback,false);assert.equal(selectScreenshots(dart.screenshots,'en-GB').fallback,false);assert.equal(selectCopy({en:{name:'Name',description:'Text'}},'ar').fallback,true);});
test('translated storefront text does not imply unsupported app languages',()=>{assert.equal(selectCopy(catalog.apps.find(a=>a.id==='starting-xi').copy,'ar').fallback,false);for(const id of ['dartlog','batting-log','baseball-order','motiontag'])assert.equal(selectCopy(catalog.apps.find(a=>a.id===id).copy,'ar').fallback,true);assert.equal(selectCopy(catalog.apps.find(a=>a.id==='starting-xi').copy,'pl').fallback,true);});

test('source app is grouped separately from four distinct other apps',()=>{for(const app of catalog.apps){for(const lang of languages){const resolved=state('?from='+app.id+'&lang='+lang);const grouped=groupApps(catalog.apps,resolved.source);assert.equal(grouped.source.id,app.id);assert.equal(grouped.others.length,4);assert.ok(!grouped.others.some(other=>other.id===app.id));assert.equal(new Set([grouped.source.id,...grouped.others.map(a=>a.id)]).size,5);assert.equal(resolved.lang,lang);}}for(const value of [null,'unknown']){const g=groupApps(catalog.apps,value);assert.equal(g.source,null);assert.equal(g.others.length,5);}});
test('source app does not infer language',()=>{for(const app of catalog.apps){assert.equal(state('?from='+app.id,['fr-FR']).lang,'fr');assert.equal(state('?from='+app.id,[]).lang,'en');}});
test('all source-flow headings are present in every UI language',()=>{for(const lang of languages){assert.ok(catalog.ui[lang].sourceHeading);assert.ok(catalog.ui[lang].otherApps);}});
